routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::resource('user','UserController');
Route::resource('cliente','ClienteController');
Route::resource('servicio','ServicioController');
Route::resource('orden','OrderController');

Route::get('/home', 'HomeController@index')->name('home');

resources/views/orden/create.blade.php
@extends('layouts.adminlte')
@section('content')
  <div class="container">
    <div class="col-sm-offset-3 col-sm-6">
      <div class="panel-title">
        <h1>Orden de Servicio --LINEAS AEREAS--</h1>
      </div>
      <div class="panel-body">
        <!--muestra validacion de errores-->
        @include('common.errors')

        <form action="{{route('orden.store')}}" method="POST">
          {{ csrf_field()}} <!--codigo de seguridad cuando se hacen peticiones al servidor-->

          <div class="form-group">
            <label for="linea_aerea" class="control-label">LINEA_AEREA </label>
            <select class="form-control" name="linea_aerea" >

              @foreach ($clientes as $cliente)
                <option  value="{{ $cliente->nombre }}">{{ $cliente->nombre }}</option>
              @endforeach
            </select>

          </div>

          <div class="form-group">  <!-- formulario que hace referencia a cliente-->
            <label for="tipo_de_avion" class="control-label">TIPO DE AVION</label>
            <input type="text" name="tipo_de_avion" class="form-control">
          </div>

          <div class="form-group">  <!-- formulario que hace referencia a cliente-->
            <label for="numero_de_vuelo" class="control-label">NUMERO DE VUELO</label>
            <input type="text" name="numero_de_vuelo" class="form-control">
          </div>

          <div class="form-group">  <!-- formulario que hace referencia a cliente-->
            <label for="matricula" class="control-label">MATRICULA</label>
            <input type="text" name="matricula" class="form-control">
          </div>

          <div class="form-group">  <!-- formulario que hace referencia a cliente-->
            <label for="tiempo_inicio" class="control-label">TIEMPO INICIO</label>
            <input type="text" name="tiempo_inicio" class="form-control">
          </div>

          <div class="form-group">  <!-- formulario que hace referencia a cliente-->
            <label for="tiempo_terminado" class="control-label">TIEMPO TERMINADO</label>
            <input type="text" name="tiempo_terminado" class="form-control">
          </div>

          <div class="form-group">  <!-- formulario que hace referencia a cliente-->
            <label for="tiempo_total" class="control-label">TIEMPO TOTAL</label>
            <input type="text" name="tiempo_total" class="form-control">
          </div>

          <div class="form-group">  <!-- formulario que hace referencia a cliente-->
            <label for="fecha" class="control-label">FECHA</label>
            <input type="text" name="fecha" class="form-control">
          </div>


          <div class="form-group">

            <button type="submit" class="btn btn-default"> <!--boton para registrar al cliente-->
              <i class="fa fa-plus"></i> registrar orden <!--registra al cliente en la fasede linea aerea-->
            </button>
          </div>
        </form>

      </div>
    </div>





  </div>

@endsection

resources/views/orden/index.blade.php
@extends('layouts.adminlte')

@section('content')
  <div class="container">
    <!-- codigo mostrar clientes-->
    <div  class="col-md-12">  <!--definimos una fila que tiene 12 columnas-->
      <!--tabla-->
      <!-- para no usar llaves en el if usamos @ en blade php-->
      @if (count($orders) >0) <!-- si la cantidad de clientes es mayor a 0  mostramos lo siguinete-->

        <div class="panel panel-default">
          <div class="panel-heading">
            REPORTE -----LISTADO DE CLINETES----- <!-- imprimimos un listado llamado clientes-->
          </div>

          <div class="panel-body">
            <table class="table table-striped task-table">
              <thead>
                <!-- tabla con dos columnas clientes y accion-->
                <th>linea_aerea</th>
                <th>tipo_de_avion</th>
                <th>numero_de_vuelo</th>
                <th>matricula</th>
                <th>tiempo_inicio</th>
                <th>tiempo_terminado</th>
                <th>tiempo_total</th>
                <th>fecha</th>
                <th>Accion</th>
              </thead>
              <tbody>
                @foreach ($orders as $cliente) <!-- aqui vamos recorriendo el listado de los clintes-->
                  <tr> <!-- indica que los clientes seran mostrados por fila dentro del codigo foreach-->
                    <td  class="table-text"><div>{{ $cliente->linea_aerea}}</div></td> <!--desplegamos el nombre del cliente-->
                    <td  class="table-text"><div>{{ $cliente->tipo_de_avion}}</div></td>
                    <td  class="table-text"><div>{{ $cliente->numero_de_vuelo}}</div></td>
                    <td  class="table-text"><div>{{ $cliente->matricula}}</div></td>
                    <td  class="table-text"><div>{{ $cliente->tiempo_inicio}}</div></td>
                    <td  class="table-text"><div>{{ $cliente->tiempo_terminado}}</div></td>
                    <td  class="table-text"><div>{{ $cliente->tiempo_total}}</div></td>
                    <td  class="table-text"><div>{{ $cliente->fecha}}</div></td>


                    <td>
                      <!--este boton redirecciona a formulario en clientes editat balde php
                      <button type="submit" class="btn btn-success" onclick="location.href='cliente/{{ $cliente->id}}'"> <!-- creamos boton para actualizar
                      <i class="fa fa-pencil"></i>editar
                    </button> -->


                    <!-- aqui implementamos el codigo para borrar clientes ingresados-->
                    <form  action="{{ ('orden')}}/{{ $cliente->id}}" method="POST"> <!--hacemos referencia clientes en web.php-->
                      {{ csrf_field()}}
                      {{method_field('DELETE')}} <!-- aca eliminamos el cliente-->

                      <button type="submit" class="btn btn-danger"> <!-- creamos boton para borrar-->
                        <i class="fa fa-trash"></i>borrar
                      </button>
                    </form>
                  </td>
                </tr>
              @endforeach

            </tbody>

          </table>

        </div>

      </div>
    @endif <!-- termina la declaracion del if-->
  </div>
  </div>



@endsection