routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::resource('user','UserController');
Route::resource('cliente','ClienteController');
Route::resource('servicio','ServicioController');
Route::resource('orden','OrderController');

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'rol_id', 'first_name','second_name','first_last_name','second_last_name','address','telephone','cellphone', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $users = \App\User::all();
    return view('user.index',compact('users'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    $rols = \App\Rol::all();
    return view('user.create',compact('rols'));
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Request $data)
  {
    $user = \App\User::create([
      'first_name' => $data['first_name'],
      'second_name' => $data['second_name'],
      'first_last_name' => $data['first_last_name'],
      'second_last_name' => $data['second_last_name'],
      'address' => $data['address'],
      'telephone' => $data['telephone'],
      'cellphone' => $data['cellphone'],
      'email' => $data['email'],
      'rol_id'=>$data['rol_id'],
      'password' => bcrypt($data['password']),
    ]);

    return redirect('user')->with('message','usuario creado con exito');
  }

  /**
  * Display the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function show($id)
  {
    $user = \App\User::find($id);
    return view('user.show',compact('user'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function edit($id)
  {
    //
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, $id)
  {
    //
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function destroy($id)
  {
    //
  }
}

resources/views/user/create.blade.php
@extends('layouts.adminlte')
@section('content')
  <div class="container">

    <h1>Crear Usuario</h1>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="panel panel-default">
            <div class="panel-heading">Crear usuario</div>

            <div class="panel-body">
              <form class="form-horizontal" method="POST" action="{{ route('user.store') }}">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('rol') ? ' has-error' : '' }}">
                  <label for="rol" class="col-md-4 control-label">Rol</label>


                  <div class="col-md-6">
                    <select class="" name="rol_id">

                    @foreach ($rols as $rol)
                      <option class="form-control" value="{{ $rol->id }}">{{ $rol->name }}</option>
                    @endforeach


                    </select>

                    @if ($errors->has('rol'))
                      <span class="help-block">
                        <strong>{{ $errors->first('rol') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
                  <label for="first_name" class="col-md-4 control-label">Primer Nombre</label>

                  <div class="col-md-6">
                    <input id="first_name" type="text" class="form-control" name="first_name" value="{{ old('first_name') }}" required autofocus>

                    @if ($errors->has('first_name'))
                      <span class="help-block">
                        <strong>{{ $errors->first('first_name') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>


                <div class="form-group{{ $errors->has('second_name') ? ' has-error' : '' }}">
                  <label for="second_name" class="col-md-4 control-label">Segundo Nombre</label>

                  <div class="col-md-6">
                    <input id="second_name" type="text" class="form-control" name="second_name" value="{{ old('second_name') }}" required autofocus>

                    @if ($errors->has('second_name'))
                      <span class="help-block">
                        <strong>{{ $errors->first('second_name') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>


                <div class="form-group{{ $errors->has('first_last_name') ? ' has-error' : '' }}">
                  <label for="first_last_name" class="col-md-4 control-label">Primer Apellido</label>

                  <div class="col-md-6">
                    <input id="first_last_name" type="text" class="form-control" name="first_last_name" value="{{ old('first_last_name') }}" required autofocus>

                    @if ($errors->has('first_last_name'))
                      <span class="help-block">
                        <strong>{{ $errors->first('first_last_name') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('second_last_name') ? ' has-error' : '' }}">
                  <label for="second_last_name" class="col-md-4 control-label">Segundo Apellido</label>

                  <div class="col-md-6">
                    <input id="second_last_name" type="text" class="form-control" name="second_last_name" value="{{ old('second_last_name') }}" required autofocus>

                    @if ($errors->has('second_last_name'))
                      <span class="help-block">
                        <strong>{{ $errors->first('second_last_name') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('telephone') ? ' has-error' : '' }}">
                  <label for="telephone" class="col-md-4 control-label">Telefono</label>

                  <div class="col-md-6">
                    <input id="telephone" type="text" class="form-control" name="telephone" value="{{ old('telephone') }}" required autofocus>

                    @if ($errors->has('telephone'))
                      <span class="help-block">
                        <strong>{{ $errors->first('telephone') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('cellphone') ? ' has-error' : '' }}">
                  <label for="cellphone" class="col-md-4 control-label">Celular</label>

                  <div class="col-md-6">
                    <input id="cellphone" type="text" class="form-control" name="cellphone" value="{{ old('cellphone') }}" required autofocus>

                    @if ($errors->has('cellphone'))
                      <span class="help-block">
                        <strong>{{ $errors->first('cellphone') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>


                <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                  <label for="address" class="col-md-4 control-label">Dirección</label>

                  <div class="col-md-6">
                    <input id="address" type="text" class="form-control" name="address" value="{{ old('address') }}" required autofocus>

                    @if ($errors->has('address'))
                      <span class="help-block">
                        <strong>{{ $errors->first('address') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>


                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                  <label for="email" class="col-md-4 control-label">Correo Electrónico</label>

                  <div class="col-md-6">
                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                    @if ($errors->has('email'))
                      <span class="help-block">
                        <strong>{{ $errors->first('email') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                  <label for="password" class="col-md-4 control-label">Contraseña</label>

                  <div class="col-md-6">
                    <input id="password" type="password" class="form-control" name="password" required>

                    @if ($errors->has('password'))
                      <span class="help-block">
                        <strong>{{ $errors->first('password') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group">
                  <label for="password-confirm" class="col-md-4 control-label">Confirmar Contraseña</label>

                  <div class="col-md-6">
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                      Crear
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.adminlte')

@section('content')
  <div class="container">
    <h1>Usuarios</h1>
    @if(Session::has('message'))
     <div class="alert alert-success alert-dismissible" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       {{Session::get('message')}}
     </div>
   @endif

   <table class='table'>
         <thead>
             <th>Nombre</th>
             <th>Apellido</th>
             <th>Telefono Celular</th>

         </thead>

         @foreach($users as $user)
             <tbody>
                 <td>{{$user->first_name}}</td>
                 <td>{{$user->first_last_name }}</td>
                 <td>{{$user->cellphone }}</td>
             </tbody>
         @endforeach
     </table>
  </div>

@endsection

resources/views/user/show.blade.php
@extends('layouts.adminlte')
@section('content')
  <div class="container">
    <h2>{{ $user->first_name }} {{ $user->first_last_name }}</h2>
  </div>
@endsection