routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::resource('user','UserController');
Route::resource('cliente','ClienteController');
Route::resource('servicio','ServicioController');
Route::resource('orden','OrderController');

Route::get('/home', 'HomeController@index')->name('home');

app/servicio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class servicio extends Model
{
  protected $table = "servicios";
  protected $fillable = [
    'id', 'nombre','tipo',
  ];   //
}

app/Http/Controllers/ServicioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ServicioController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $servicios = \App\servicio::all();
    return view('servicio.index',compact('servicios'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    return view('servicio.create');
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Request $request)
  {
    $servicio = \App\Servicio::create([
      'nombre' => $request['nombre'],
      'tipo' => $request['tipo'],

    ]);
    return redirect('servicio')->with('message','Servicio creado con exito');
  }

  /**
  * Display the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function show($id)
  {
    $user = \App\Servicio::find($id);
    return view('servicio.show',compact('servicio'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function edit($id)
  {
    //
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, $id)
  {
    //
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function destroy($id)
  {
    //
  }
}

resources/views/servicio/create.blade.php
@extends('layouts.adminlte')
@section('content')
  <div class="container">

    <h1>Crear Servicio</h1>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="panel panel-default">
            <div class="panel-heading">Crear Servicio</div>

            <div class="panel-body">
              <form class="form-horizontal" method="POST" action="{{ route('servicio.store') }}">
                {{ csrf_field() }}


                <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                  <label for="nombre" class="col-md-4 control-label">Nombre Servicio</label>

                  <div class="col-md-6">
                    <input id="nombre" type="text" class="form-control" name="nombre" value="{{ old('nombre') }}" required autofocus>

                    @if ($errors->has('nombre'))
                      <span class="help-block">
                        <strong>{{ $errors->first('nombre') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('tipo') ? ' has-error' : '' }}">
                  <label for="tipo" class="col-md-4 control-label">Tipo Servicio</label>

                  <div class="col-md-6">
                    <input id="tipo" type="text" class="form-control" name="tipo" value="{{ old('tipo') }}" required autofocus>

                    @if ($errors->has('tipo'))
                      <span class="help-block">
                        <strong>{{ $errors->first('tipo') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                      Crear
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/servicio/index.blade.php
@extends('layouts.adminlte')

@section('content')
  <div class="container">
    <h1>Clientes</h1>
    @if(Session::has('message'))
     <div class="alert alert-success alert-dismissible" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       {{Session::get('message')}}
     </div>
   @endif

   <table class='table'>
         <thead>
             <th>Nombre Servicio</th>
             <th>Tipo Servicio</th>

         </thead>

         @foreach($servicios as $servicio)
             <tbody>
                 <td>{{$servicio->nombre}}</td>
                 <td>{{$servicio->tipo}}</td>
             </tbody>
         @endforeach
     </table>
  </div>

@endsection

resources/views/servicio/show.blade.php
@extends('layouts.adminlte')
@section('content')
  <div class="container">
    <h2>{{ $servicio->nombre }} {{ $servicio->tipo }}</h2>
  </div>
@endsection