routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::resource('user','UserController');
Route::resource('cliente','ClienteController');
Route::resource('servicio','ServicioController');
Route::resource('orden','OrderController');

Route::get('/home', 'HomeController@index')->name('home');

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
protected $table = "clientes";
protected $fillable = [
      'id', 'nombre','descripcion',
    ];   //
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    $clientes = \App\Cliente::all();    
    return view('cliente.index',compact('clientes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    return view('cliente.create');   
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    $cliente = \App\Cliente::create([
      'nombre' => $request['nombre'],
      'descripcion' => $request['descripcion'],

    ]);
    return redirect('cliente')->with('message','Cliente creado con exito');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    $user = \App\Cliente::find($id);
    return view('cliente.show',compact('cliente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/cliente/create.blade.php
@extends('layouts.adminlte')
@section('content')
  <div class="container">

    <h1>Crear Cliente</h1>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="panel panel-default">
            <div class="panel-heading">Crear cliente</div>

            <div class="panel-body">
              <form class="form-horizontal" method="POST" action="{{ route('cliente.store') }}">
                {{ csrf_field() }}


                <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                  <label for="nombre" class="col-md-4 control-label">Nombre Cliente</label>

                  <div class="col-md-6">
                    <input id="nombre" type="text" class="form-control" name="nombre" value="{{ old('nombre') }}" required autofocus>

                    @if ($errors->has('nombre'))
                      <span class="help-block">
                        <strong>{{ $errors->first('nombre') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('descripcion') ? ' has-error' : '' }}">
                  <label for="descripcion" class="col-md-4 control-label">Descripcion</label>

                  <div class="col-md-6">
                    <input id="descripcion" type="text" class="form-control" name="descripcion" value="{{ old('descripcion') }}" required autofocus>

                    @if ($errors->has('descripcion'))
                      <span class="help-block">
                        <strong>{{ $errors->first('descripcion') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                      Crear
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/cliente/index.blade.php
@extends('layouts.adminlte')

@section('content')
  <div class="container">
    <h1>Clientes</h1>
    @if(Session::has('message'))
     <div class="alert alert-success alert-dismissible" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       {{Session::get('message')}}
     </div>
   @endif

   <table class='table'>
         <thead>
             <th>Nombre Cliente</th>
             <th>Descripcion</th>

         </thead>

         @foreach($clientes as $cliente)
             <tbody>
                 <td>{{$cliente->nombre}}</td>
                 <td>{{$cliente->descripcion}}</td>
             </tbody>
         @endforeach
     </table>
  </div>

@endsection

resources/views/cliente/show.blade.php
@extends('layouts.adminlte')
@section('content')
  <div class="container">
    <h2>{{ $cliente->nombre }} {{ $cliente->descripcion }}</h2>
  </div>
@endsection